import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'backend.settings')
django.setup()

from courses.models import Course, Module, Lesson

course = Course.objects.get(title="Rust on STM32")

def get_module(order):
    return Module.objects.get(course=course, order=order)

def update_lesson(module_order, lesson_order, content_dict):
    mod = get_module(module_order)
    lesson = Lesson.objects.get(module=mod, order=lesson_order)
    lesson.explanation_html = content_dict.get('explanation_html', '')
    lesson.challenges_html = content_dict.get('challenges_html', '')
    lesson.assignments_html = content_dict.get('assignments_html', '')
    lesson.mcqs_html = content_dict.get('mcqs_html', '')
    lesson.save()
    print(f"Updated Lesson: {lesson.title}")

# ==========================================
# MODULE 4: STM32 Basics
# ==========================================
m4_l1 = {
    "explanation_html": """
    <img src="https://images.unsplash.com/photo-1592503254549-ecf1245b0e00?w=800&q=80" alt="Memory Chip" style="width:100%; border-radius:8px; margin-bottom:1rem;">
    <h3>Memory Mapping</h3>
    <p>Unlike a PC where software asks the OS to do things, on bare metal, software writes directly to hardware via <strong>Memory-Mapped I/O</strong>.</p>
    <p>If you want to turn on an LED, you don't call <code>turn_on_led()</code> at the CPU level. Instead, you write a specific bit to a specific hexadecimal memory address (e.g., <code>0x4002_0014</code> for GPIOA Output Data Register on STM32F4). In Rust, we use crates generated by <a href="https://github.com/rust-embedded/svd2rust" target="_blank">svd2rust</a> to do this safely.</p>
    """,
    "challenges_html": "<ol>" + "".join([f"<li>Challenge 4.1.{i}: Identify the base address for GPIOA on your board's datasheet.</li>" for i in range(1, 11)]) + "</ol>",
    "assignments_html": "<ol><li>Download the Reference Manual for your specific STM32 chip.</li><li>Locate the memory map section.</li><li>Find the address for the RCC (Reset and Clock Control) peripheral.</li></ol>",
    "mcqs_html": "<ol>" + "".join([f"<li><strong>MCQ 4.1.{i}</strong>: What is Memory Mapped I/O? (A) Writing to RAM to control hardware, (B) Using a hard drive. Answer: A</li>" for i in range(1, 11)]) + "</ol>"
}

m4_l2 = {
    "explanation_html": """
    <h3>Reading Datasheets</h3>
    <p>To master embedded programming, you must become comfortable with the <strong>Reference Manual (RM)</strong> and the <strong>Datasheet (DS)</strong>.</p>
    <ul>
        <li><strong>Datasheet:</strong> Pinouts, electrical limits (voltage, current), and physical package details.</li>
        <li><strong>Reference Manual:</strong> How to program the chip. Registers, bits, and configuration flow. (Usually 1,000+ pages!)</li>
    </ul>
    """,
    "challenges_html": "<ol>" + "".join([f"<li>Challenge 4.2.{i}: Find the maximum current a single GPIO pin can source on your board.</li>" for i in range(1, 11)]) + "</ol>",
    "assignments_html": "<ol><li>Find the pin mapping for the user LED (e.g., PA5).</li><li>Find the Alternate Function mapping for UART2.</li><li>Submit the page numbers where you found them.</li></ol>",
    "mcqs_html": "<ol>" + "".join([f"<li><strong>MCQ 4.2.{i}</strong>: Which document explains how to program the registers? (A) Datasheet, (B) Reference Manual. Answer: B</li>" for i in range(1, 11)]) + "</ol>"
}

m4_l3 = {
    "explanation_html": """
    <h3>Reset and Startup Flow</h3>
    <p>When power is applied, the STM32 fetches the initial Stack Pointer and the Reset Vector (address of the first instruction) from the very beginning of Flash memory (address <code>0x0800_0000</code>).</p>
    <p>The <a href="https://github.com/rust-embedded/cortex-m-rt" target="_blank">cortex-m-rt</a> crate handles all of this automatically, initializing static variables in RAM and then calling your <code>#[entry]</code> function.</p>
    """,
    "challenges_html": "<ol>" + "".join([f"<li>Challenge 4.3.{i}: What is the Vector Table?</li>" for i in range(1, 11)]) + "</ol>",
    "assignments_html": "<ol><li>Explain the difference between .text, .data, and .bss sections.</li><li>Draw a diagram of the boot sequence.</li><li>Identify where the Stack pointer starts in memory.</li></ol>",
    "mcqs_html": "<ol>" + "".join([f"<li><strong>MCQ 4.3.{i}</strong>: What crate handles the startup routine in Rust? (A) cortex-m-rt, (B) std. Answer: A</li>" for i in range(1, 11)]) + "</ol>"
}

update_lesson(4, 1, m4_l1)
update_lesson(4, 2, m4_l2)
update_lesson(4, 3, m4_l3)

# ==========================================
# MODULE 5: Setup and First Build
# ==========================================
m5_l1 = {
    "explanation_html": """
    <img src="https://images.unsplash.com/photo-1550645612-83f5d594b671?w=800&q=80" alt="Terminal code" style="width:100%; border-radius:8px; margin-bottom:1rem;">
    <h3>Rust Embedded Toolchain</h3>
    <p>We need a cross-compiler. Your PC runs x86_64, but the STM32 runs ARM Cortex-M. Use rustup to add the target:</p>
    <pre style="background: #111; padding: 1rem; border-radius: 8px; color: #00f0ff;"><code>rustup target add thumbv7em-none-eabihf</code></pre>
    <p>This specifically targets ARM Cortex-M4 and M7 with hardware floating point (the 'hf').</p>
    """,
    "challenges_html": "<ol>" + "".join([f"<li>Challenge 5.1.{i}: Find the correct target triple for an STM32F103 (Cortex-M3).</li>" for i in range(1, 11)]) + "</ol>",
    "assignments_html": "<ol><li>Install the target via rustup.</li><li>Install cargo-binutils.</li><li>Install probe-rs.</li></ol>",
    "mcqs_html": "<ol>" + "".join([f"<li><strong>MCQ 5.1.{i}</strong>: What does 'hf' stand for in the target name? (A) High frequency, (B) Hardware floating point. Answer: B</li>" for i in range(1, 11)]) + "</ol>"
}

m5_l2 = {
    "explanation_html": """
    <h3>Configuring Cargo (config.toml and memory.x)</h3>
    <p>We tell cargo to always build for our ARM target by editing <code>.cargo/config.toml</code>.</p>
    <p>We also need a <code>memory.x</code> file. This linker script tells the compiler exactly where Flash and RAM are located on your specific chip.</p>
    <pre style="background: #111; padding: 1rem; border-radius: 8px; color: #00f0ff;"><code>MEMORY
{
  FLASH : ORIGIN = 0x08000000, LENGTH = 512K
  RAM : ORIGIN = 0x20000000, LENGTH = 128K
}</code></pre>
    """,
    "challenges_html": "<ol>" + "".join([f"<li>Challenge 5.2.{i}: Write a memory.x file for a chip with 1MB Flash and 256KB RAM.</li>" for i in range(1, 11)]) + "</ol>",
    "assignments_html": "<ol><li>Create a new project using cargo-generate.</li><li>Update memory.x to match your board.</li><li>Update config.toml with the correct target.</li></ol>",
    "mcqs_html": "<ol>" + "".join([f"<li><strong>MCQ 5.2.{i}</strong>: What does memory.x do? (A) Linker script for memory layout, (B) Allocates heap. Answer: A</li>" for i in range(1, 11)]) + "</ol>"
}

m5_l3 = {
    "explanation_html": """
    <h3>Common Setup Mistakes</h3>
    <p>The most common errors beginners face:</p>
    <ul>
        <li><strong>Wrong Target:</strong> Building for x86 instead of ARM. (Check `.cargo/config.toml`).</li>
        <li><strong>Missing memory.x:</strong> Linker fails because it doesn't know where to put the code.</li>
        <li><strong>Probe not found:</strong> USB permissions on Linux (udev rules) are incorrect.</li>
    </ul>
    """,
    "challenges_html": "<ol>" + "".join([f"<li>Challenge 5.3.{i}: What is a udev rule and why do you need it on Linux for ST-LINK?</li>" for i in range(1, 11)]) + "</ol>",
    "assignments_html": "<ol><li>Verify probe-rs detects your board by running `probe-rs info`.</li><li>Fix udev rules if on Linux.</li><li>Take a screenshot of the successful detection.</li></ol>",
    "mcqs_html": "<ol>" + "".join([f"<li><strong>MCQ 5.3.{i}</strong>: Why might `cargo build` fail with linker errors on a new project? (A) Missing memory.x, (B) Missing std. Answer: A</li>" for i in range(1, 11)]) + "</ol>"
}

update_lesson(5, 1, m5_l1)
update_lesson(5, 2, m5_l2)
update_lesson(5, 3, m5_l3)

# ==========================================
# MODULE 6: First Embedded Project
# ==========================================
m6_l1 = {
    "explanation_html": """
    <img src="https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80" alt="Blinking LED" style="width:100%; border-radius:8px; margin-bottom:1rem;">
    <h3>Project Structure & Entry Point</h3>
    <p>Embedded Rust programs don't have a standard `main()` function because there's no OS to call it. Instead, we use the `#[entry]` macro from `cortex-m-rt`.</p>
    <pre style="background: #111; padding: 1rem; border-radius: 8px; color: #00f0ff;"><code>#![no_std]
#![no_main]

use cortex_m_rt::entry;
use panic_halt as _;

#[entry]
fn main() -> ! {
    // Initialization code here
    loop {
        // Event loop
    }
}</code></pre>
    """,
    "challenges_html": "<ol>" + "".join([f"<li>Challenge 6.1.{i}: Explain why #[no_main] is required.</li>" for i in range(1, 11)]) + "</ol>",
    "assignments_html": "<ol><li>Set up the boilerplate code above.</li><li>Ensure it compiles with `cargo build`.</li></ol>",
    "mcqs_html": "<ol>" + "".join([f"<li><strong>MCQ 6.1.{i}</strong>: What macro defines the start of the program? (A) #[main], (B) #[entry]. Answer: B</li>" for i in range(1, 11)]) + "</ol>"
}

m6_l2 = {
    "explanation_html": """
    <h3>Blink LED</h3>
    <p>Here is how you blink an LED using the STM32F4xx HAL crate.</p>
    <pre style="background: #111; padding: 1rem; border-radius: 8px; color: #00f0ff;"><code>use stm32f4xx_hal::{pac, prelude::*};

#[entry]
fn main() -> ! {
    let dp = pac::Peripherals::take().unwrap();
    let gpioa = dp.GPIOA.split();
    let mut led = gpioa.pa5.into_push_pull_output();
    
    loop {
        led.set_high();
        // (add delay here)
        led.set_low();
        // (add delay here)
    }
}</code></pre>
    <p>Notice <code>Peripherals::take()</code>. This ensures you are the exclusive owner of the hardware registers!</p>
    """,
    "challenges_html": "<ol>" + "".join([f"<li>Challenge 6.2.{i}: Change the LED pin to PB13.</li>" for i in range(1, 11)]) + "</ol>",
    "assignments_html": "<ol><li>Write the complete Blink LED code.</li><li>Add a dummy delay loop (busy wait).</li><li>Submit your `src/main.rs`.</li></ol>",
    "mcqs_html": "<ol>" + "".join([f"<li><strong>MCQ 6.2.{i}</strong>: Why do we `unwrap()` on `Peripherals::take()`? (A) It can only be taken once safely. Answer: A</li>" for i in range(1, 11)]) + "</ol>"
}

m6_l3 = {
    "explanation_html": """
    <h3>Flashing and Verifying</h3>
    <p>If you have configured `.cargo/config.toml` to use `probe-rs`, simply typing <code>cargo run</code> will compile the code, flash it to the board via SWD, and open a debug terminal.</p>
    <p>If the LED blinks, congratulations! You have successfully written and deployed bare-metal Rust firmware.</p>
    """,
    "challenges_html": "<ol>" + "".join([f"<li>Challenge 6.3.{i}: Try changing the delay loop size and observe the blink rate.</li>" for i in range(1, 11)]) + "</ol>",
    "assignments_html": "<ol><li>Run `cargo run`.</li><li>Record a 5-second video of your blinking LED.</li><li>Submit the video link.</li></ol>",
    "mcqs_html": "<ol>" + "".join([f"<li><strong>MCQ 6.3.{i}</strong>: What command compiles and flashes in one step with probe-rs? (A) cargo flash, (B) cargo run. Answer: B</li>" for i in range(1, 11)]) + "</ol>"
}

update_lesson(6, 1, m6_l1)
update_lesson(6, 2, m6_l2)
update_lesson(6, 3, m6_l3)

print("Batch 2 (Modules 4, 5, 6) Seeded successfully with code snippets and structure!")
